import { Inter } from "next/font/google";
import "./globals.css";
import SmothScroling from "./components/SmothScroll";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <SmothScroling>
        {children}
        </SmothScroling>
       

      </body>
    </html>
  );
}
