import  PortfolioCard from '../components/Portfolio';
// or Dynamic metadata
export async function generateMetadata({ params }) {
    return {
      title: 'Portfolio Page',
      description: "Generated by create Portfolio Page",
    }
  }
const Portfolio = () => {
    return (
       <div>
        <div className="relative px-4  sm:px-20 py-10 sm:py-16 lg:py-28  bg-custom  bg-cover bg-center bg-no-repeat">
            <div className="absolute inset-0 bg-black bg-opacity-80"></div>
            <div className="relative z-10">
                <h2 className="text-[26px] sm:text-32px] text-[#E9FF97]"> Portfolio</h2>
                <p className="text-white py-2 lg:w-1/2">
                As our website looks attractive from a computer, it can be easily used with mobiles, tablets and tabs. We listen to the needs of our clients and give them the right guidance as well as make video tutorials on how to use it after application development. development and software for their customers on demand.
                </p>
            </div>
        </div>
        <PortfolioCard/>
       </div>
    );
};

export default Portfolio;
